# Use latest Node LTS to build
FROM node:lts AS builder

WORKDIR /app

# Copy package.json and package-lock.json
COPY /webui ./

# Install dependencies
# RUN npm install

# Copy the rest of the app files
COPY . .

# Build the Vue app
RUN npm run build-prod

# Create final container
FROM nginx:alpine

# Copy the built artifacts from the previous stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# CMD is not needed for nginx image, it starts automatically
