openapi: 3.0.3

info:
    title: WasaPhoto - OpenAPI 3.0
    description: | 
      This is the api specification for WasaPhoto, an educational purpose based project, 
      to keep in touch with your friends by sharing photos of special moments.  

      - [The github private project repository] (https://github.com/luigidannibale/Wasa)
    version: "1"
    contact:
      email: dannibale.1991254@studenti.uniroma1.it

externalDocs:
  description: Find out more about project specification
  url: http://gamificationlab.uniroma1.it/notes/Project.pdf
    
#servers:
#    - url:
#    description:

paths:
    #doLogin
    /users/:
      post:
        operationId: doLogin
        tags: 
          - user
        summary: Logs in a user
        description: |-
          If the user does not exist, it will be created,
          and an identifier is returned.
          If the user exists, the user identifier is returned.        
        requestBody:
          description: User details
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
                  
        responses:
          "200":
            description: User log-in action successful
            content:
              application/json:
                schema:
                    $ref: "#/components/schemas/User/properties/id"
          "201":
            description: New user log-in action successful
            content:
              application/json:
                schema:
                    $ref: "#/components/schemas/User/properties/id"
          "400": 
            description: Bad request
    
    #getUserProfile
    /users/getUserProfile/:
      get:
        operationId: getUserProfile
        tags: 
          - user
        summary: Finds a user by Id
        description: |
          If the user id exists, the user is returned.        
        parameters:
          - name: userID
            in: query
            description: The id of the user to find 
            required: true
            schema:
              $ref : "#/components/schemas/User/properties/id"
        responses: 
          "200":
            description: Successfully found the user
            content:
              application/json:      
                schema:
                  $ref : "#/components/schemas/User"
          "400":
            description: Bad request
          "404":
            description: Not found

    #getMyStream    
    /users/{userID}/getMyStream:
      parameters:
        - $ref : "#/components/parameters/userID"
      get:
        operationId: getMyStream
        tags:
          - user
        summary: Gets the user his stream 
        description: |
          Takes an user id and returns his stream as array of photos
        responses:
          "200":
            description: Successfully returning the stream
            content:
              application/json:
                schema:
                  type: array
                  items: 
                    $ref : "#/components/schemas/Photo"
          "400":
            description: Bad request

    #setMyUserName
    /users/{userID}/:
      parameters:
      - $ref : "#/components/parameters/userID"
      put:
        operationId: setMyUserName
        tags:
          - user
        summary: Changes the username
        description: |
          Takes a user (by the id) and a new name and sets the name as the new username of such user        
        parameters:
          - name: username 
            in: query
            description: Name to set to the user
            required: true
            schema:
              $ref : "#/components/schemas/User/properties/username"
        responses:
          "200":
            description: Successful
          "400":
            description: Bad request
    
    #followUser
    #unfollowUser
    /users/{userID}/followed/{followedID}/:
      parameters:
      - $ref : "#/components/parameters/userID"
      - $ref : "#/components/parameters/followedID"
      put:
        operationId: followUser
        tags:
          - user
        summary: Follows a user
        description: |
          Takes the id of a user, if it exists, the actual user starts following the given user (if was already following nothing happens)
        responses:
          "200": 
            description: Successful, already was following
          "201":
            description: Successful, started following
          "400":
            description: Bad request
          "404":
            description: User to follow not found            
      delete:
        operationId: unfollowUser
        tags:
          - user
        summary: Unfollows a user
        description: |
          Takes the id of a user, if it is followed by the actual user, the actual user unfollows the given user (if wasn't already following nothing happens)
        responses:
          "200": 
            description: Successful, already not followed
          "201":
            description: Successful, unfollowed
          "400":
            description: Bad request          

    #banUser
    #unbanUser
    /users/{userID}/banned/{bannedID}/:
      parameters:
      - $ref : "#/components/parameters/userID"
      - $ref : "#/components/parameters/bannedID"

      put:
        operationId: banUser
        tags:
          - user 
        summary: Bans a user
        description: |
          Takes the id of a user, if it exists, the actual user bans the given user (if was already banned nothing happens)
        responses:
          "200": 
            description: Successful, already banned
          "201":
            description: Successful, banned
          "400":
            description: Bad request
          "404":
            description: User to ban not found
      delete:
        operationId: unbanUser
        tags:
          - user
        summary: Unbans a user
        description: |
          Takes the id of a user, if it is banned by the actual user, the actual user unbans the given user (if wasn't already banned nothing happens)
        responses:
          "200": 
            description: Successful, already not banned
          "201":
            description: Successful, unbanned
          "400":
            description: Bad request 
     
    #uploadPhoto
    #deletePhoto
    /photos/:      
      post:
        tags:
          - photos
        summary: Post a new photo
        description: |
          Posts a new photo and returns the id of the posted photo
        operationId: uploadPhoto
        requestBody:
          content:
            multipart/form-data :
              schema:
                type: string
                format: binary
        responses:
          "201":
            description: Photo posted successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Photo/properties/id'
          "400":
            description : "Bad request"          
      delete:
        tags:
          - photos
        description: "Deletes an existing photo"
        summary: Deletes a photo
        operationId: deletePhoto
        parameters:
          - name: photoID
            in: query
            required: true
            schema:
              type: integer
        responses:
          "200":
            description: Successful
          "400":
            description: "Bad request"
          "404":
            description: "Not found"
          "500":
            description: "Server error"    
    
    #likePhoto
    /photos/{photoID}/likes/:
      parameters:
        - $ref : "#/components/parameters/photoID"
      put:
        operationId: likePhoto
        tags: 
          - photos
        summary: Puts a like to a photo
        description: |
          Takes a userID and creates a like of that user to the photo, 
          if such user has already liked the photo, nothing happens.
        parameters:
          - name: userID
            in: query
            schema:
              $ref : "#/components/schemas/User/properties/id"
        responses:
          "200":
            description: Successful, already like
            content:
              application/json:
                schema:
                  $ref : "#/components/schemas/Like/properties/id"
          "201":
            description: Successfully liked the photo
            content:
              application/json:
                schema:
                  $ref : "#/components/schemas/Like/properties/id"
          "400":
            description: Bad request
          "401":
            description: User has no authorization to like this photo
          "404":
            description: User not found
    
    #getLike
    #unlikePhoto
    /photos/{photoID}/likes/{likeID}/:
      parameters: 
        - $ref : "#/components/parameters/photoID"
        - $ref : "#/components/parameters/likeID"
      
      get:
        operationId: getLike
        tags: 
          - photos 
        summary: Gets the like details
        description: Takes a like id and returns the like 
        responses:
          "200":
            description:  Success, returning the like
            content:
              application/json:
                schema:
                   $ref : "#/components/schemas/Like"
        
      delete:
        operationId: unlikePhoto
        tags:
          - photos
        summary: Deletes a like to the photo
        description: |
          Takes a userID, if it matches the user that has put the like, the like is deleted,
          otherwise nothing happens.
        parameters:
          - name: userID
            in: query
            schema:
              $ref : "#/components/schemas/User/properties/id"
        responses:
          "200":
            description: Success, photo unliked
          "400":
            description: Bad request
          "401":
            description: User requesting the elimination of the like has no authorization
    
    #commentPhoto
    /photos/{photoID}/comments/:
      parameters:
        - $ref : "#/components/parameters/photoID"
      post:
        operationId: commentPhoto
        tags: 
          - photos
        summary: Comments a photo
        description: |
          Takes a userID and the text message of the comment and creates 
          a new comment of that user to the photo.
        parameters:
          - name: userID
            in: query
            schema:
              $ref : "#/components/schemas/User/properties/id"
          - name: text-message
            in: query
            schema:
              $ref : "#/components/schemas/Comment/properties/text-message"
        responses:
          "201":
            description: Successful, commment created, returning id
            content:
              application/json:
                schema:
                  $ref : "#/components/schemas/Comment/properties/id"
          "400":
            description: Bad request
          "401":
            description: User has no authorization to comment this photo
          "404":
            description: User not found
    
    #getComment
    #uncommentPhoto
    /photos/{photoID}/comments/{commentID}/:
      parameters: 
        - $ref : "#/components/parameters/photoID"
        - $ref : "#/components/parameters/commentID"
      
      get:
        operationId: getComment
        tags: 
          - photos 
        summary: Gets the comment details
        description: Takes a comment id and returns the comment
        responses:
          "200":
            description:  Success, returning the comment
            content:
              application/json:
                schema:
                   $ref : "#/components/schemas/Comment"
        
      delete:
        operationId: uncommentPhoto
        tags:
          - photos
        summary: Deletes a comment to the photo
        description: |
          Takes a userID, if it matches the user that has posted the comment, the comment is deleted,
          otherwise nothing happens.
        parameters:
          - name: userID
            in: query
            schema:
              $ref : "#/components/schemas/User/properties/id"
        responses:
          "200":
            description: Success, comment deleted
          "400":
            description: Bad request
          "401":
            description: User requesting the elimination of the comment has no authorization
    

components:  
  parameters:
    userID: 
      name: userID
      in: path
      description: Id of the user
      required: true
      schema:
        $ref : "#/components/schemas/User/properties/id"
    followedID: 
      name: followedID
      in: path
      description: Id of the followed user
      required: true
      schema:
        $ref : "#/components/schemas/User/properties/id"
    bannedID: 
      name: bannedID
      in: path
      description: Id of the banned user
      required: true
      schema:
        $ref : "#/components/schemas/User/properties/id"
    photoID:
      name: photoID
      in: path
      description: ID of the photo
      required: true
      schema:
        $ref : "#/components/schemas/Photo/properties/id"
    likeID:
      name: likeID
      in: path
      description: ID of the like
      required: true
      schema:
        $ref : "#/components/schemas/Like/properties/id"
    commentID:
      name: commentID
      in: path
      description: ID of the comment
      required: true
      schema:
        $ref : "#/components/schemas/Comment/properties/id"
  
  schemas:
      User:          
        type: object
        properties:
          id:
            type: string
            example: ab1wd
            readOnly: true          
          username:
            type: string
            example: Maria
            pattern: Ë† .*? $
            minLength: 3
            maxLength: 16
      Photo: 
        type: object 
        properties:
          id:
            type: string
            example: wvd12
            readOnly: true
          image:
            description: The actual image of the photo
            type: string
            format: binary
          upload-timestamp:
            type: object
            schema:
              $ref: "#/components/schemas/Date"
      Like:
        type: object
        properties:
          id:
            type: string
            example: as32
            readOnly: true
          userID:
            $ref : "#/components/schemas/User/properties/id"
      Comment:
        type: object
        properties:
          id:
            type: string
            example: as32
            readOnly: true
          userID:
            $ref : "#/components/schemas/User/properties/id"
          text-message:
            type: string
      Date:
        year:
          type: integer            
        month:
          type: enum
          val:
            - January
            - February','March','April','May','June','July','August','September','October','November','December']}
        yet to finish
